services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    ports:
      - "8080:8080"
    volumes:
      - $HOME/.local:/home/coder/.local
      - $HOME/.config:/home/coder/.config
      - $HOME/Docker:/home/coder/project
    user: "$(id -u):$(id -g)"
    environment:
      - DOCKER_USER=$USER
      - PASSWORD=${CODE_SERVER_PASSWORD:-password}
    command: --bind-addr 0.0.0.0:8080 --auth password /home/coder/project
