services:
  ddns-go:
    container_name: ddns-go
    image: jeessy/ddns-go
    restart: always
    network_mode: host
    ports:
      - 9876:9876
    volumes:
      - ./ddns-go:/root
    environment:
      TZ: Asia/Shanghai
