version: '3.8'  # バージョンを指定

services:
  discord-bot:
    image: ghcr.io/hououinkami/docker/discord-bot:latest  # 使用するイメージ
    container_name: discord-bot  # コンテナ名
    environment:  # 環境変数を指定
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - SOURCE_CHANNEL_ID=${SOURCE_CHANNEL_ID}
      - TARGET_CHANNEL_ID=${TARGET_CHANNEL_ID}
    restart: unless-stopped  # コンテナが停止した場合の再起動ポリシー
