version: '3.9'

services:
  gewechat:
    image: ghcr.io/0ekk/wechotd/wechotd:latest
    container_name: gewe
    volumes:
      - ./temp:/root/temp
    ports:
      - "2531:2531"  # API服务端口
      - "2532:2532"  # 文件下载服务端口
    environment:
      TZ: Asia/Shanghai
    restart: always
