version: '3.9'

services:
  gewe:
    image: registry.cn-chengdu.aliyuncs.com/tu1h/wechotd:alpine
    container_name: gewe
    ports:
      - "2531:2531"
      - "2532:2532"
    volumes:
      - ./temp:/root/temp
    restart: always
