version: "3.8"

services:
  # 如果有现成的 Postgresql 实例，可以删除这一小节
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      TZ: Asia/Shanghai
    volumes:
      - ./postgresql_icqq:/var/lib/postgresql/data

  sign:
    container_name: sign
    image: ghcr.io/clansty/qsign
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - TZ=Asia/Shanghai
    
  q2tg:
    container_name: q2tg
    image: ghcr.io/clansty/q2tg:sha-4fb3afb
    # image: ghcr.io/clansty/q2tg:sleepyfox
    # platform: linux/amd64
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      # 如果要使用 RICH_HEADER 需要将端口发布到公网
      - 8080:8080
    volumes:
      - ./q2tg:/app/data
      - ./cache:/app/.config/QQ/NapCat/temp
      - /var/run/docker.sock:/var/run/docker.sock
      # arm兼容
      # - ./patches:/app/patches
      # - ./main/package.json:/app/main/package.json
      - ./ui:/app/ui
      # - ./main/tsconfig.json:/app/main/tsconfig.json
      - ./main/build.ts:/app/main/build.ts
      # - ./main/prisma:/app/main/prisma
      - ./main/src:/app/main/src
      # - ./main/prisma:/app/prisma
      # - ./docker-entrypoint.sh :/app/entrypoint.sh
    environment:
      - TG_API_ID=${TG_API_ID}
      - TG_API_HASH=${TG_API_HASH}
      - TG_BOT_TOKEN=${TG_BOT_TOKEN}
      - TG_INITIAL_DCID=5
      - TG_INITIAL_SERVER=91.108.56.174
      - DATABASE_URL=postgres://user:password@postgres/db_name
      - SIGN_API=http://sign:4848/sign?key=114514
      - SIGN_VER=9.0.56
      # - SIGN_API=https://qsign.chahuyun.cn/?key=miraibbs&ver=9.0.90
      # - SIGN_VER=9.0.90
      # - SIGN_API=https://hlhs-nb.cn/signed/?key=114514
      # - SIGN_VER=9.0.70
      - TG_CONNECTION=tcp # 连接 Telegram 的方式，也可以改成 websocket
      # 如果你需要使用 /flags set RICH_HEADER 来显示头像，或者正确显示合并转发的消息记录，则需将 q2tg 8080 端口发布到公网，可以使用 cloudflare tunnel
      # 请尽量配置这个服务
      - WEB_ENDPOINT=${WEB_ENDPOINT} # 填写你发布到公网的域名
      - CRV_VIEWER_APP=${CRV_VIEWER_APP}
      # DEPRECATED: 请使用 WEB_ENDPOINT
      #- CRV_API=${CRV_API}
      #- CRV_KEY=${CRV_KEY}
      # 要关闭文件上传提示，请取消注释以下变量 https://github.com/clansty/Q2TG/issues/153
      #- DISABLE_FILE_UPLOAD_TIP=1
      # 如果需要通过代理联网，那么设置下面两个变量
      #- PROXY_IP=
      #- PROXY_PORT=
      # 代理联网认证，有需要请修改下面两个变量
      #- PROXY_USERNAME=
      #- PROXY_PASSWORD=
      - TZ=Asia/Shanghai
      
  tunnel: #如果沒有使用 Cloudflare Tunnel 暴露內網端口，請直接刪除此區塊
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN} 
      - TZ=Asia/Shanghai
