services:
  code-server:
    image: codercom/code-server:latest
    container_name: code-server
    ports:
      - "8070:8080"
    environment:
      - PASSWORD=${CODE_SERVER_PASSWORD}
    volumes:
      - ${CODE_SERVER_PATH}:/home/coder/project
    command: --bind-addr 0.0.0.0:8080 --auth password /home/coder/project
