services:
  wx2tg-pad:
    image: ${IMAGE_NAME:-finalpi/wechat2tg-pad:latest}
    container_name: wx2tg-pad
    volumes:
      - ./config:/app/storage
      - ./save-files:/app/save-files # 保存文件夹挂载后贴纸文件不需要重新转换
      - ./src:${CONTAINER_DIR:-/app/src_temp} # 调试用
      - ./sticker:/app/sticker # 贴纸映射信息
    env_file: ".env"
    # ports:
    #  - "3080:3000"
    environment:
      TZ: Asia/Shanghai
      BOT_TOKEN: ${TG_BOT_TOKEN}
      API_ID: ${TG_API_ID}
      API_HASH: ${TG_API_HASH}
      # 代理配置(可选)
      # 协议socks5,http,https
      # PROXY_PROTOCOL=socks5
      # PROXY_HOST=
      # PROXY_PORT=
      # PROXY_USERNAME=
      # PROXY_PASSWORD=
      # 自定义消息模板配置:(#[alias]:联系人备注,#[name]:联系人昵称,#[topic]:群聊昵称,#[alias_first]:备注优先,如果没有备注就显示联系人的昵称)
      ## 群消息格式
      ROOM_MESSAGE: '<blockquote><b>🌐#[topic]</b> —— <b>👤#[alias_first]</b></blockquote>'
      ## 公众号消息格式
      OFFICIAL_MESSAGE: '<blockquote><b>📣#[name]</b></blockquote>'
      ## 联系人消息格式
      CONTACT_MESSAGE: '<blockquote><b>👤#[alias_first]</b></blockquote>'
      ## 群消息格式(群组下)
      ROOM_MESSAGE_GROUP: '<blockquote><b>👤#[alias_first]</b></blockquote>'
      ## 公众号消息格式(群组下)
      OFFICIAL_MESSAGE_GROUP: ' '
      ## 联系人消息格式(群组下)
      CONTACT_MESSAGE_GROUP: ' '
      ## 自动创建微信群组的名称格式
      CREATE_ROOM_NAME: '#[alias_first]'
      ## 自动创建联系人群组的名称格式
      CREATE_CONTACT_NAME: '#[alias_first]'
      ## 文字消息显示格式:#[identity]身份文本,#[body]:消息文本,#[br]换行
      MESSAGE_DISPLAY: '#[identity]#[br]#[body]'
      # Gewechaty
      BASE_API: 'http://wx2tg-server:8058/api'
      # 调试模式（默认false）
      DEBUG_MODE: ${DEBUG_MODE:-false}
      # 自己的微信ID
      MY_WXID: ${MY_WXID}
    restart: unless-stopped

  wx2tg-server:
    image: finalpi/wx2tg-server:latest # 拉取镜像
    container_name: wx2tg-server
    ports:
      - "18058:8058"
    volumes:
      - ./conf:/usr/wic-go/conf
    restart: unless-stopped
    depends_on:
      - wx2tg-redis

  wx2tg-redis:
    image: redis:7.2
    container_name: wx2tg-redis
    ports:
      - "127.0.0.1:16379:6379"
    volumes:
      - ./redis_data:/data
    command: redis-server --appendonly yes --rename-command FLUSHALL "" --rename-command FLUSHDB ""
    restart: unless-stopped