services:
  wechat2tg:
    image: ${IMAGE_NAME:-finalpi/wechat2tg-pad:latest}
    container_name: wx2tg
    volumes:
      - ./config:/app/storage
      - ./save-files:/app/save-files # 保存文件夹挂载后贴纸文件不需要重新转换
      - ./src:${CONTAINER_DIR:-/app/src_temp} # 调试用
      - ./sticker:/app/sticker # 贴纸映射信息
    env_file: ".env"
    # ports:
    #  - "3080:3000"
    environment:
      TZ: Asia/Shanghai
      BOT_TOKEN: ${TG_BOT_TOKEN}
      API_ID: ${TG_API_ID}
      API_HASH: ${TG_API_HASH}
      # 代理配置(可选)
      # 协议socks5,http,https
      # PROXY_PROTOCOL=socks5
      # PROXY_HOST=
      # PROXY_PORT=
      # PROXY_USERNAME=
      # PROXY_PASSWORD=
      # 自定义消息模板配置:(#[alias]:联系人备注,#[name]:联系人昵称,#[topic]:群聊昵称,#[alias_first]:备注优先,如果没有备注就显示联系人的昵称)
      ## 群消息格式
      ROOM_MESSAGE: '<blockquote><b>🌐#[topic]</b> —— <b>👤#[alias_first]</b></blockquote>'
      ## 公众号消息格式
      OFFICIAL_MESSAGE: '<blockquote><b>📣#[name]</b></blockquote>'
      ## 联系人消息格式
      CONTACT_MESSAGE: '<blockquote><b>👤#[alias_first]</b></blockquote>'
      ## 群消息格式(群组下)
      ROOM_MESSAGE_GROUP: '<blockquote><b>👤#[alias_first]</b></blockquote>'
      ## 公众号消息格式(群组下)
      OFFICIAL_MESSAGE_GROUP: ' '
      ## 联系人消息格式(群组下)
      CONTACT_MESSAGE_GROUP: ' '
      ## 自动创建微信群组的名称格式
      CREATE_ROOM_NAME: '#[alias_first]'
      ## 自动创建联系人群组的名称格式
      CREATE_CONTACT_NAME: '#[alias_first]'
      ## 文字消息显示格式:#[identity]身份文本,#[body]:消息文本,#[br]换行
      MESSAGE_DISPLAY: '#[identity]#[br]#[body]'
      # Gewechaty
      BASE_API: 'http://xxxbot:9011/VXAPI'
      FILE_API: ''
      CALLBACK_API: 'http://10.0.0.1:8088/wx849/callback'
      # 调试模式（默认false）
      DEBUG_MODE: ${DEBUG_MODE:-false}
    restart: unless-stopped
  xxxbot:
    image: nanssye/xxxbot-pad:latest
    container_name: xxxbot
    restart: unless-stopped
    pull_policy: always # 确保每次都检查并拉取最新的镜像
    ports:
      - "9090:9090" # 管理后台端口
      - "3000:3000" # WeTTy终端端口
      # - "8088:8088" # 回调端口
      - "9011:9011" # WechatAPI服务器端口
    volumes:
      - ./xxxbot/main_config.toml:/app/main_config.toml # 主配置文件
      - ./xxxbot/bot_status_admin.json:/app/admin/bot_status.json # 管理后台使用的机器人状态文件
      - ./xxxbot/bot_status.json:/app/bot_status.json # 主程序使用的机器人状态文件
      - ./xxxbot/robot_stat.json:/app/resource/robot_stat.json # 微信账号信息文件
      - ./xxxbot/login_stat.json:/app/WechatAPI/Client/login_stat.json # 登录状态文件
      - ./xxxbot/wx849_callback_daemon.py:/app/wx849_callback_daemon.py
      - ./xxxbot/wx849_callback_config.json:/app/wx849_callback_config.json
      - ./xxxbot/redis:/app/849/redis/appendonlydir # Redis数据
      - ./xxxbot/avatars:/app/resource/avatars # 头像文件
      - ./xxxbot/plugins:/app/plugins # 插件
      - ./xxxbot/dow:/app/dow # 插件
      - ./xxxbot/logs:/app/logs # log
      - ./xxx_redis_data:/var/lib/redis # Redishuancun 
    environment:
      TZ: Asia/Shanghai
      ADMIN_USERNAME: ${XXX_USERNAME}
      ADMIN_PASSWORD: ${XXX_PASSWORD}
