name: Build and Push Docker Image

on:
  # push:
    # branches:
    #   - main
    # path:
    #   - .*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # GitHubのユーザー名
          password: ${{ secrets.GITHUB_TOKEN }}  # GitHubのトークン

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/discord-bot .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/${{ github.repository }}/discord-bot
