name: Build gewe Image

on:
  workflow_dispatch:
    inputs:
      compile_all_branches:
        description: 'true: latest + alpine; false: alpine'
        required: true
        default: false
        type: boolean
  # schedule:
  #   - cron: '0 0 * * *'

env:
  TZ: Asia/Shanghai

permissions:
  packages: write
  contents: write  # 需要写入权限来更新文件

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        # - branch: main
        #   tag: main
        - branch: alpine
          tag: latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Check if image needs update
        id: check_image
        run: |
          # 获取镜像的 Digest
          PULL_OUTPUT=$(docker pull registry.cn-hangzhou.aliyuncs.com/gewe/gewe:latest || echo "Failed to pull")
          echo "$PULL_OUTPUT"
          
          # 提取 Digest 值
          CURRENT_DIGEST=$(echo "$PULL_OUTPUT" | grep "Digest:" | awk '{print $2}')
          echo "Current image digest: $CURRENT_DIGEST"
          
          # 检查文件是否存在，不存在则创建
          if [ ! -f wx2tg/geweVer.txt ]; then
            echo "geweVer.txt does not exist, creating it"
            mkdir -p wx2tg
            echo "" > wx2tg/geweVer.txt
          fi
          
          # 读取存储的 Digest
          STORED_DIGEST=$(cat wx2tg/geweVer.txt)
          echo "Stored digest: $STORED_DIGEST"
          
          # 比较 Digest
          if [ "$CURRENT_DIGEST" != "$STORED_DIGEST" ]; then
            echo "Digest changed, update needed"
            echo "needs_update=true" >> $GITHUB_OUTPUT
            echo "current_digest=$CURRENT_DIGEST" >> $GITHUB_OUTPUT
          else
            echo "Digest unchanged, no update needed"
            echo "needs_update=false" >> $GITHUB_OUTPUT
          fi
    
      - name: Clone external repository
        if: ${{ (inputs.compile_all_branches == 'true' || matrix.branch == 'alpine') && steps.check_image.outputs.needs_update == 'true' }}
        run: |
          git clone https://github.com/0ekk/wechotd.git
          cd wechotd
          git checkout ${{ matrix.branch }}

      - name: Set up Docker Buildx
        if: ${{ steps.check_image.outputs.needs_update == 'true' }}
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        if: ${{ steps.check_image.outputs.needs_update == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to DockerHub
        if: ${{ steps.check_image.outputs.needs_update == 'true' }}
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Time Info
        if: ${{ steps.check_image.outputs.needs_update == 'true' }}
        run: echo "TIME_INFO=$(date +'%m%d%H%M')" >> $GITHUB_ENV
        
      - name: Build and push
        id: build
        if: ${{ (inputs.compile_all_branches == 'true' || matrix.branch == 'alpine') && steps.check_image.outputs.needs_update == 'true' }}
        uses: docker/build-push-action@v5
        with:
          context: ./wechotd
          file: ./wechotd/Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            hououinkami/gewe:${{ matrix.tag }}
            hououinkami/gewe:${{ matrix.tag }}-${{ env.TIME_INFO }}
          #   ghcr.io/${{ github.repository_owner }}/gewe:${{ matrix.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Update Digest in Repository
        if: ${{ steps.check_image.outputs.needs_update == 'true' && steps.build.outcome == 'success' }}
        run: |
          # 更新 Digest 到文件
          echo "${{ steps.check_image.outputs.current_digest }}" > wx2tg/geweVer.txt
          
          # 配置 Git
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # 提交更改
          git add wx2tg/geweVer.txt
          git commit -m "Update gewe image digest [skip ci]"
          git push
          
      - name: Send Telegram Notification
        if: ${{ steps.build.outcome == 'success' && steps.check_image.outputs.needs_update == 'true' }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "✅ GeWechatのビルドに成功しました！"
          format: "html"
