name: Build gewe Image

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'

permissions:
  packages: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - branch: main
          tag: latest
        - branch: alpine
          tag: alpine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Clone external repository
        run: |
          git clone https://github.com/0ekk/wechotd.git
          cd wechotd
          git checkout ${{ matrix.branch }}  # 检出矩阵中定义的分支

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # 使用你的 GitHub 用户名
          password: ${{ secrets.GITHUB_TOKEN }}  # 自动生成的 Token

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./wechotd
          file: ./wechotd/Dockerfile
          push: true
          platforms: linux/amd64, linux/arm64
          tags: |
            hououinkami/gewechat:${{ matrix.tag }}
          #   ghcr.io/${{ github.repository_owner }}/gewechat:${{ matrix.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
