name: Build wx2tg Image for Share

on:
  workflow_dispatch:
    inputs:
      build_multi_arch:
        description: '同时编译 AMD64 和 ARM64 平台'
        required: false
        default: false
        type: boolean

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone repo
        run: |
          git clone https://github.com/hououinkami/wechat2tg.git
          cd wechat2tg
          git checkout wx2tg-pad-dev

      - name: Modify files
        working-directory: wx2tg
        run: |
          chmod +x modify.sh
          source ./modify.sh
          awk_script=''
          cd ../wechat2tg/src
          adaptFile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      - name: Generate Time Info
        run: echo "TIME_INFO=$(date +'%m%d%H%M')" >> $GITHUB_ENV
        
      - name: Set platforms
        id: set-platforms
        run: |
          if [ "${{ github.event.inputs.build_multi_arch }}" == "true" ]; then
            echo "PLATFORMS=linux/amd64,linux/arm64/v8" >> $GITHUB_ENV
            echo "使用多平台构建: AMD64 和 ARM64"
          else
            echo "PLATFORMS=linux/amd64" >> $GITHUB_ENV
            echo "仅使用 AMD64 平台构建"
          fi

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./wechat2tg
          file: ./wechat2tg/Dockerfile
          push: true
          tags: |
            hououinkami/wechat2tg-pad:latest
          platforms: ${{ env.PLATFORMS }}
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
      
      - name: Send Telegram Notification
        if: steps.build.outcome == 'success'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "✅ WeChat2TG（共有用）のビルドに成功しました！"
          format: "html"
