name: Build wx2tg Image

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone repo
        run: |
          git clone https://github.com/finalpi/wechat2tg.git
          cd wechat2tg
          git checkout wx2tg-pad-dev

      - name: Copy utils.ts
        run: |
          cp ../wx2tg/utils.ts ./src/client/utils.ts

      - name: Modify WechatClient.ts
        run: |
          cd ./src/client
          awk '
            NR == 1 {
                print "import { translateMessageType } from '\''./utils'\'';"
            }
            /emoji\.gif/ {
                gsub(/emoji\.gif/, "ステッカー.gif");
            }
            /收到一条/ {
                print "const translatedType = translateMessageType(msg.type());";
                gsub(/收到一条/, "");
                gsub(/消息，请在手机上查看/, "");
                gsub(/\$\{msg\.type\(\)\}/, "[${translatedType}]");
            }
            { print }
          ' WechatClient.ts > temp && mv temp WechatClient.ts

      - name: Modify TelegramBotClient.ts
        run: |
          awk '
            /temp_file/ {
                gsub(/temp_file/, "ファイル");
            }
            /文件接收中/ {
                gsub(/文件接收中/, ""); 
            }
            /使用文件传输助手接收/ {
                gsub(/使用文件传输助手接收/, "ファイル転送で受信"); 
            }
            { print }
          ' TelegramBotClient.ts > temp && mv temp TelegramBotClient.ts
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV

      - name: Generate Time Info
        run: echo "TIME_INFO=$(date +'%m%d%H%M')" >> $GITHUB_ENV
        
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./wechat2tg
          file: ./wechat2tg/Dockerfile
          push: true
          tags: |
            hououinkami/wechat2tg-pad:latest
            hououinkami/wechat2tg-pad:${{ env.TIME_INFO }}
          platforms: linux/arm64/v8
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
