name: Build XXXBot Image

on:
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clone repo
        run: |
          git clone https://github.com/NanSsye/XXXBot.git
          cd XXXBot

      - name: Modify files
        working-directory: wx2tg
        run: |
          ls

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate Time Info
        run: echo "TIME_INFO=$(date +'%m%d%H%M')" >> $GITHUB_ENV
        
      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ./XXXBot
          file: ./XXXBot/Dockerfile
          push: true
          tags: |
            hououinkami/xxxbot:kami
          # hououinkami/xxxbot:${{ env.TIME_INFO }}
          platforms: linux/arm64/v8
          # cache-from: type=local,src=/tmp/.buildx-cache
          # cache-to: type=local,mode=max,dest=/tmp/.buildx-cache
      
      - name: Send Telegram Notification
        if: steps.build.outcome == 'success'
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "✅ XXXBotのビルドに成功しました！"
          format: "html"